spring.application.name=studentAPI
#application.properties = brain of your app configuration


#Database connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

#Automatically creates/updates tables
#update → create table if not exist, update if changed
spring.jpa.hibernate.ddl-auto=update

#prints SQL queries in console
spring.jpa.show-sql=true

#makes SQL prettier in console
spring.jpa.properties.hibernate.format_sql=true

#sets Swagger UI URL
springdoc.swagger-ui.path=/swagger-ui.html